### ISSUE TITLE
\cite completion using F9

### ISSUE THREAD

**Issue by catanzaro** [vim-latex/vim-latex#110]
I apologize if this is not the right place for this, but I cannot get the F9 auto completion to work when the cursor is placed on `\cite{`. The two split windows open, and I can scroll through them with `j` and `k` but pressing `enter` returns to `\cite{` with nothing entered. The `n` and `p` keys don't do anything, as well as sorting by the `f` key as mentioned in the Latex-Suite reference. This issue has been addressed previously on [vi stackexchange](https://vi.stackexchange.com/questions/11762/latex-suite-cite-completion-not-inserting-result?newreg=9ce117c8c1044975b340a3f8b5811316) and [tex stackexchange](https://tex.stackexchange.com/questions/7479/latex-suite-on-osx-citation-completion-not-working) with no answers.

I have python2 and python3 installed, a compatible vim installation, and all other functionality of latex-suite. With the debugger running, the following is the output after typing `\cite{` and then `F9`

>view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : +Tex_ScanFileForCite: searching for bibkeys in Data_Research_Statement.tex (buffer #1)
view : Tex_ScanFileForCite: found bibliography command in Data_Research_Statement.tex
view : trying to search through [research.bib]
view : finding .bib file [Data_Research_Statement.tex]
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
view : +Tex_SetupCWindow
view : +Tex_SyncPreviewWindow
view : :Tex_CompleteRefCiteCustom: completing with 
view : :Tex_SwitchToInsertMode:

**Comment by gerw** [comment]
What do
`:echo Tex_UsePython()`
and
`:echo Tex_GetVarValue('Tex_UseCiteCompletionVer2')`
say (after opening a tex-file)?

**Comment by catanzaro** [comment]
`:echo Tex_UsePython()`
gives 0
`:echo Tex_GetVarValue('Tex_UseCiteCompletionVer2')`
gives 1

and just in case 
`:echo has('python')` and `:echo has('python3')`
both give 1

**Comment by gerw** [comment]
What about
`:echo Tex_GetVarValue('Tex_UsePython')`
?

**Comment by catanzaro** [comment]
That also gives 0.

**Comment by gerw** [comment]
But this is weird. In https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/texrc#L60, this variable is set to `1`.

**Comment by catanzaro** [comment]
My configuration doesn't but it was set to 0 in my ~/vim tree. I have no idea why. 

I'm going to do a clean install of vim-latex just to be sure. Thanks for your help in tracking this down

**Comment by catanzaro** [comment]
Unfortunately, now I get the errors mentioned [here](https://github.com/vim-latex/vim-latex/issues/60) and [here](https://github.com/vim-latex/vim-latex/issues/104). You were right before when you said that somehow python is broken in vim. Thanks anyways

**Comment by gerw** [comment]
In both issues, a different error is described. What do you get exactly?

**Comment by catanzaro** [comment]
First, sorry about listing both errors. I get the precisely the error of [#104.](https://github.com/vim-latex/vim-latex/issues/104) Here is my minimal example:

```
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\addbibresource{test.bib}
\begin{document}
\cite{}
\end{document}
```
with test.bib
```
@book{diller97,
    author = "Antoni Diller",
    title = "{\LaTeX} Line by Line",
    year = "1997",
    edition = "1st",
    publisher = "Wiley",
    address = "Chichester, England"
}

@book{goossens99,
    author = "Michel Goossens and Sebastian Rahtz",
    title = "The {\LaTeX} Web Companion",
    year = "1999",
    edition = "1st",
    publisher = "Addison-Wesley",
    address = "Boston, Massachusetts"
}
```
Pressing `F9` gives
```
(a) all (f) filter (s) sort (n) next (p) previous (q) quit (<CR>) choose
Press ENTER or type command to continue
```
Pressing `a` brings up a split window with the error of #104 :
```
Error detected while processing function Tex_HandleBibShortcuts:
line   47:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
line   48:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
Error detected while processing function Tex_HandleBibShortcuts..Tex_DisplayBibList:
line   21:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
```
On the other hand, in contrast to #104 when I type `:echo Tex_FindBibFiles()` it prints `test.bib` . My debug-log is 
```
proj : texproject.vim: catching LatexSuiteFileType event
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.000252 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
pack : :Tex_pack_updateall: split
pack : +Tex_ScanForPackages
pack : :Tex_ScanForPackages: Begining scans in [test.tex], beginline = 4
pack : :Tex_ScanForPackages: beginning scan for \usepackage lines
pack : :Tex_ScanForPackages: found package(s) ["biblatex"] on line 2
pack : :Tex_ScanForPackages: End scan \usepackage, detected packages = ,biblatex
pack : :Tex_ScanForPackages: Beginning scan for \newcommand's
pack : :Tex_ScanForPackages: Beginning scan for \newenvironment's
pack : -Tex_ScanForPackages
pack : :Tex_pack_updateall: detected [biblatex] in first run
pack : :Tex_pack_updateall: scanning package biblatex
pack : :Tex_pack_updateall: silent! find biblatex.sty
pack : :Tex_pack_updateall: present file = test.tex
pack : :Tex_pack_updateall: biblatex not found anywhere
pack : Tex_pack_check: searching for biblatex in dictionaries/ in &rtp
pack : :Tex_pack_updateall: throwing LatexSuiteScannedPackages event
pack : -Tex_pack_updateall
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
view : Tex_FindBibFiles: found bibliography command in test.tex
view : :Tex_FindBibFiles: trying to search through [test.bib]
view : :Tex_FindBibFiles: returning [test.bib
]
view : :Tex_FindBibFiles: 
view : Tex_FindBibFiles: found bibliography command in test.tex
view : :Tex_FindBibFiles: trying to search through [test.bib]
view : :Tex_FindBibFiles: returning [test.bib
]
```
I'm running on Vim 8.0 on Windows 10

**Comment by gerw** [comment]
Thank you. Can you also try my suggestions from https://github.com/vim-latex/vim-latex/issues/104#issuecomment-332496673?

**Comment by catanzaro** [comment]
Just to reiterate, `:echo Tex_FindBibFiles()` correctly displays `test.bib` As for your comments on the other post:

`:py print Tex_BibFile` and `:py3 print(Tex_BibFile)' both give
```
Error detected while processing function Tex_HandleBibShortcuts:
line   47:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
line   48:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
Error detected while processing function Tex_HandleBibShortcuts[49]..Tex_DisplayBibList:
line   21:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
```

Creating the variable gives
```
Traceback (most recent call last):
  File "C:\Users\m\AppData\Local\Programs\Python\Python35-32\Lib\urllib\requ
est.py", line 1410, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Program Files (x86)/Vim/vimfiles/ftplugin/latex-suite\bibtools.py", l
ine 196, in __init__
    self.addfile(f)
  File "C:/Program Files (x86)/Vim/vimfiles/ftplugin/latex-suite\bibtools.py", l
ine 199, in addfile
    fields = urlopen('file://' + quote(os.path.abspath(file))).read().decode('ut
f-8').split('@')
  File "C:\Users\m\AppData\Local\Programs\Python\Python35-32\Lib\urllib\requ
est.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\m\AppData\Local\Programs\Python\Python35-32\Lib\urllib\requ
est.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\m\AppData\Local\Programs\Python\Python35-32\Lib\urllib\requ
est.py", line 484, in _open
    '_open', req)
  File "C:\Users\m\AppData\Local\Programs\Python\Python35-32\Lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\m\AppData\Local\Programs\Python\Python35-32\Lib\urllib\request.py", line 1388, in file_open
    return self.open_local_file(req)
  File "C:\Users\m\AppData\Local\Programs\Python\Python35-32\Lib\urllib\request.py", line 1427, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] The system cannot find the path specified: ''>
```

Calling directly from the command line gives
```
python bibtools.py C:\Users\m\test.bib
Traceback (most recent call last):
  File "bibtools.py", line 248, in <module>
    bf = BibFile(sys.argv[1])
  File "bibtools.py", line 196, in __init__
    self.addfile(f)
  File "bibtools.py", line 199, in addfile
    fields = urlopen('file://' + quote(os.path.abspath(file))).read().decode('utf-8').split('@')
  File "C:\Python27\lib\urllib.py", line 86, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 460, in open_file
    return self.open_ftp(url)
  File "C:\Python27\lib\urllib.py", line 519, in open_ftp
    host = socket.gethostbyname(host)
IOError: [Errno socket error] [Errno 11001] getaddrinfo failed
```
and
```
python3 bibtools.py C:\Users\m\test.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 1474, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Vim\vimfiles\ftplugin\latex-suite\bibtools.py", line 248, in <module>
    bf = BibFile(sys.argv[1])
  File "C:\Program Files (x86)\Vim\vimfiles\ftplugin\latex-suite\bibtools.py", line 196, in __init__
    self.addfile(f)
  File "C:\Program Files (x86)\Vim\vimfiles\ftplugin\latex-suite\bibtools.py", line 199, in addfile
    fields = urlopen('file://' + quote(os.path.abspath(file))).read().decode('utf-8').split('@')
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 1452, in file_open
    return self.open_local_file(req)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 1491, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] The system cannot find the path specified: ''>

**Comment by gerw** [comment]
You are using a (very) old version of `bibtools.py`. One year ago, `quote()` in line 199 has been changed to `pathname2url()`. Please update your installation of latex-suite. Does this fix your error?

**Comment by catanzaro** [comment]
Yes, it does. Wow, sorry for that frustratingly simple fix.
